### ISSUE TITLE
INSTALL doc in .gitignore yet mentioned in README

### ISSUE THREAD

**Issue by carmoca** [westes/flex#130]
# INSTALL doc in .gitignore yet mentioned in README

The README file mentions reviewing the INSTALL document yet the file is not in the repo. Noticed that the INSTALL document is an entry in the '.gitignore' file.

Fixes are:
1. Edit the README to address how to "install" flex
    1. Remove mentions of the INSTALL doc from the README file
1. Create an actual INSTALL document (or retrieve from a previous commit)

**Comment by westes** [comment]
The INSTALL doc is the generic document provided by autoconf. It's picked up when ./autogen.sh is run. This is intentional and correct. There will likely be some additions to the manual given the switches that have been added lately, but I'm good with that being in the manual and not in the INSTALL doc.
