### ISSUE TITLE
register keyword usage

### ISSUE THREAD

**Issue by darakian** [westes/flex#132]
I've just joined a project which uses the flex lexer and I'm noticing that the register keyword is used in the generated lexer c++ code. As far as I'm aware the register keyword is deprecated. Is there a flag which can be used to prevent this?

**Comment by westes** [comment]
Which version of flex is the project using? I know register was removed a while ago from flex, so that's worth checking.

There is no switch, but if it's still in the codebase, please submit a pr to remove it.

On Monday,  5 December 2016,  6:01 am -0800, Jon Moroney <notifications@github.com> wrote:

> I've just joined a project which uses the flex lexer and I'm noticing that the register keyword is used in the generated lexer c++ code. As far as I'm aware the register keyword is deprecated. Is there a flag which can be used to prevent this?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/132

-- 
Will Estes
westes575@gmail.com

**Comment by darakian** [comment]
Currently testing with
flex 2.5.35 Apple(flex-31)
