### ISSUE TITLE
make--Error 126

### ISSUE THREAD

**Issue by chenjinlei** [westes/flex#136]
my configuration: CC=arm-linux-gcc ./configure --host=arm-linux
and then "make"
`Making all in lib
make[1]: Entering directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/lib'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/lib'
Making all in src
make[1]: Entering directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/src'
make  all-am
make[2]: Entering directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/src'
../src/stage1flex -o stage1scan.c stage1scan.l
../src/stage1flex: ../src/stage1flex: cannot execute binary file
make[2]: *** [stage1scan.c] Error 126
make[2]: Leaving directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home3/chenjinlei/Trunk_16.2/rootfs/flex-2.6.1/src'
make: *** [all-recursive] Error 1`

**Comment by chenjinlei** [comment]
and I do not use `autogen.sh`, just configure and make.

**Comment by westes** [comment]
Are you trying to cross compile? There are known issues with that if so.

**Comment by chenjinlei** [comment]
yeah, I try to cross compile it to arm platform. I'll check this, and could you show me the issues related to this?

**Comment by Explorer09** [comment]
This should be marked as a duplicate to #78.
Unfortunately, because I know nothing about your build system, so you have to test by yourself to see if workaround works. Here you go: [Commit](https://github.com/westes/flex/commit/5ddb7cee2f44e1491d3c4b452ad3a409bee41788) ([patch](https://github.com/westes/flex/commit/5ddb7cee2f44e1491d3c4b452ad3a409bee41788.patch))

**Comment by chenjinlei** [comment]
thanks alot!
