### ISSUE TITLE
2.6.4 milestone near empty?

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#203]
I don't want to offend anyone, just asking...

I wanted to get an overview what changes will be part of 2.6.4 and therefore checked https://github.com/westes/flex/milestone/3 - but there is only one closed and one open issue assigned.
Do you use the milestones or do you manually go through all the changes when creating the release announcement?

It seems there are at least two possible severe issues with 2.6.3 (#142 and #178) - is there a list somewhere with "known issues" of different versions? I think about updating flex (we use 2.5.39) and creating a pro/contra list is likely a good thing to do...

**Comment by westes** [comment]
2.6.4 will be cut from the tip of master once I get there.

I am aiming at using the milestones to describe what will be included in releases. There are some small pull requests that I am processing today because they've been sitting there for a while and they are small. It was somewhere after 2.6.3 that I started using the milestones, so 2.6.4 is going to include a bunch of things that never got labeled as such.

On Tuesday,  2 May 2017, 12:24 pm -0700, Simon Sobisch <notifications@github.com> wrote:

> I don't want to offend anyone, just asking...
> 
> I wanted to get an overview what changes will be part of 2.6.4 and therefore checked https://github.com/westes/flex/milestone/3 - but there is only one closed and one open issue assigned.
> Do you use the milestones or do you manually go through all the changes when creating the release announcement?
> 
> It seems there are at least two possible severe issues with 2.6.3 (#142 and #178) - is there a list somewhere with "known issues" of different versions? I think about updating flex (we use 2.5.39) and creating a pro/contra list is likely a good thing to do...
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/203

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
OK, therefore I guess everything in 2.6.5 will be labeled, correct?
Is the requested list of know issues (ideally not only for 2.6.4 but for older versions, too) available somewhere?

**Comment by westes** [comment]
Since there are some big things that the current tip of master includes, it is worth doing a release to fix those.
