### ISSUE TITLE
Incorrect handling of 8-bit characters in v2.6.4

### ISSUE THREAD

**Issue by jameslarus** [westes/flex#298]
The conversion in the macro:

#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

is not sufficient to " Promotes a possibly negative, possibly signed char to an  integer in range [0..255] for use as an array index." If the character has its high-bit set (e.g. "perché"), you get a negative index, with unpredictable results. 

A better alternative is:

#define YY_SC_TO_UI(c) ((YY_CHAR) (c & 0xff))

**Comment by Explorer09** [comment]
For two's complement machines, the cast from signed char to unsigned has a predictable result. Bit truncation are done implicitly.

The problem would be that we can't know the character encoding that user has been using in the higher level. Although Flex allows generating 8-bit scanners, the encoding is not explicitly specified (there's no need to say that Flex is not yet UTF-8 compatible).

I think you better specify an actual case that breaks, rather than an example that does have predictable behavior as far as I know.

**Comment by westes** [comment]
Can you give an example that breaks? You'll have to provide the steps to reproduce the breaking behavior since it will likely depend on the particular options used.

**Comment by jameslarus** [comment]
I took a closer look at the problem. The cause was that my scanner redefined YY_CHAR

#define YY_CHAR char

This worked fine (for 25 years), but a recent version broke backward compatibility. This is probably not a big deal, since YY_CHAR wasn't documented.
