### ISSUE TITLE
Is the required gettext version too high?

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#334]
The release announcement for 2.6.4 says:

> We have lowered the versions of automake and gettext that
configure.ac lists as required for building flex.

Still configure.ac has `AM_GNU_GETTEXT_VERSION([0.19.7])`.
Is there a specific reason for it? To compile from master I had to lower it to `0.18.3` and got no errors or warning when running `autogen.sh` / `po/update_linguas.sh` `make dist-gzip` (there's no lzip on this machine and the lz target is always active).

**Comment by westes** [comment]
There have been some security fixes in gettext. There is also a squirrely issue with using old versions of gettext that I can't quite track down. I'm also loathed to purposely keep old versions of gettext around just so that flex's build system can be kept happy. That makes maintaining my own configuration harder and would require keeping the travis build system in a similar state.
