### ISSUE TITLE
yyinput is broken in buffer-only scenarios (using yywrap to switch buffers)

### ISSUE THREAD

**Issue by esohns** [westes/flex#525]
yyinput() is broken when using yy_scan_buffer() (i.e. yyin == NULL) in conjunction with yywrap().

The problematic call sequence seems to be as follows: yy_scan_buffer() sets yy_fill_buffer to 0, but this flag is reset to 1 in yy_init_buffer(), which is called via yyrestart() (called in turn via yy_get_next_buffer()). Now, when yy_fill_buffer equals 1, YY_INPUT (i.e. read(fileno (yyin))) is invoked in yy_get_next_buffer (), which leads to a crash.

One possible fix might be to only set yy_fill_buffer to 1 in yy_init_buffer() iff yyin is not NULL. I am not sure however, whether there are other issues to consider besides setting yy_fill_buffer.

**Comment by Mightyjo** [comment]
Do you have a test case or a scanner I can use to build a test case for the regression tests? Should be an easy fix and those would really help make sure it sticks.

**Comment by esohns** [comment]
sorry; in the mean time I have adapted my scanner to not use yyinput at all. I was using yyinput to skip over data bytes in the parsed buffer(s) for efficiency reasons; now I parse every single byte instead.

One example use case would be to match some characters and then repeatedly invoke yyinput inside of the rule block until yywrap gets invoked. This should trigger the crash; not 100% sure about this though.

I still hope we can get this fixed so I can revert back to a version with better performance.

**Comment by esohns** [comment]
I have cobbled together a scanner that should expose the issue. Note that it still contains some pseudo-code. Let me know if you need more details.

[bug_yyinput.zip](https://github.com/westes/flex/files/8695829/bug_yyinput.zip)

**Comment by Mightyjo** [comment]
Can you check that [this new test](https://github.com/Mightyjo/flex/blob/issue-525/tests/yywrap_r.i3.l) captures the behavior you reported? Just want to be sure I'm not fixing another bug altogether :)

**Comment by Mightyjo** [comment]
Assuming my example matches your problem, this is more difficult to solve than I thought. I [coded up your suggestion](https://github.com/Mightyjo/flex/blob/issue-525/tests/yywrap_r.i3.l) in yy_init_buffer but it causes early termination with the yywrap implementation in the test. (I need to fix the spacing. Take a look at src/c99-flex.skl, too.) No SEGV, at least!

You might have to let yylex return to main, set up the next buffer, then call yylex again. Testing that.

**Comment by Mightyjo** [comment]
It works without calling yywrap in the user code, but when flex does the call it's followed by yyrestart and the rule has to be matched again so you see ECHO called for each buffer. Either way tests the problem code path.

Testing yyin == NULL is the right thing to do. It only happens when user code bypasses the default initialization that would have set up stdin. yy_is_our_buffer is used by the scanner's memory manager and I don't want to overload it's meaning.

The main thing I've fixed is the SEGV if you don't check the return value of yyinput. You'll just get a scanner failure now because it hits EOF unexpectedly.

**Comment by Mightyjo** [comment]
DOH! I'm using %option prefix="test" and pushed code without yywrap renamed. Not really sure why that's working at all.

**Comment by Mightyjo** [comment]
Okay, updated the test to use the automatic yywrap behavior. You still have to check whether you've gone past your last buffer somehow. I used the do-it-yourself example from the Multiple Input Buffers section of the manual. You could instead prepare all your buffers on the stack and have yywrap pop the stack to move to the next one. 

I badly needed coffee earlier. I can use yywrap and testwrap interchangeably inside the module produced from my .l file because -of course - flex inserted the #defines above my code. That would not necessarily be true with testwrap and main implemented in a separate .c file. I updated their definitions to be consistent with my options.
