### ISSUE TITLE
flex 2.6.1 does not cross compile

### ISSUE THREAD

**Issue by hobbitalastair** [westes/flex#78]
As of 53e3088, flex runs stage1flex to bootstrap itself. Unfortunately, this fails when cross compiling, as stage1flex is built for the target architecture (not for the host machine).

I'm unsure how to fix this as my knowledge of GNU autotools is limited; but http://lists.gnu.org/archive/html/automake/2008-12/msg00016.html seems to suggest a way to make this work.

**Comment by tobijk** [comment]
Looking at how difficult it seems to fix the build system, maybe it could just be documented in an INSTALL.CROSS how to work around it. Something like this seems to work reasonably well:

    # generate native stage1flex
    ./configure \
        --disable-nls \
        --prefix=/tools \
        --enable-shared 

    make -C lib
    make -C src stage1flex
    mv src/stage1flex src/stage1flex.build
    make distclean

    # generate cross flex
    ./configure \
        --disable-nls \
        --prefix=/tools \
        --enable-shared \
        --with-sysroot="$SYSROOT_DIR" \
        --host="$TARGET_CROSS_TRIPLET"

    make -C lib -j"$PARALLEL_JOBS"
    make -C src -j"$PARALLEL_JOBS" || true
    mv src/stage1flex.build src/stage1flex
    touch src/stage1flex
    make -C src -j"$PARALLEL_JOBS"

Instead of selectively building `lib` and `src`, one could possibly manually remove the `tests` folder from the `SUBDIRS` variable in the Makefile and compile all through.
